# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2cd2cb79689efeea022722c31884914f74e6346dd51c11a157fc2e0738611967b8c7b1be901d26dcad4f4f57e45418169b812a13af962d1f69fff4af74793f2

test:
  secret_key_base: f7ad67b5f07b23f62a41237484ca654b047273dda00e47775acdc9342798f3e4dd7ad1d5162e521e4426dad68cd09766065f31d8de7f7413b6dc45c78eab1593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
